# Perceptron

[Perceptron: A Simple Neural Network](https://www.youtube.com/watch?v=kft1AJ9WVDk)

[Original Code: GitHub](https://github.com/jonasbostoen/simple-neural-network/blob/master/training_version.py)

[How to build a simple neural network](https://medium.com/technology-invention-and-more/how-to-build-a-simple-neural-network-in-9-lines-of-python-code-cc8f23647ca1)

[What is Perceptron: A BeginnersTutorial For Perceptron](https://medium.com/mlearning-ai/what-is-perceptron-a-beginnerstutorial-for-perceptron-632539884146)

[What the Hell is Perceptron?](https://towardsdatascience.com/what-the-hell-is-perceptron-626217814f53)


## Setting Up Necessary Things

In [1]:
# Ignore All Warnings
import warnings
warnings.filterwarnings("ignore")

## Necessary Imports

In [2]:
# For Numerical
import numpy as np

## Data

In [16]:
# Input Data
train_x = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
])

print("Training Input: ")
train_x

Training Input: 


array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [17]:
# Output Data
train_y = np.array([[0, 1, 1, 0]]).T

print("Training Output: ")
train_y

Training Output: 


array([[0],
       [1],
       [1],
       [0]])

## Weights

In [18]:
# Seed random numbers
np.random.seed(42)

# Initialize weights randomly
synaptic_weights = 2 * np.random.random((3, 1)) - 1

In [19]:
# Synaptic weights
print("Synaptic weights: ")
synaptic_weights

Synaptic weights: 


array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

## Perceptron

In [20]:
# Sigmoid Function to normalize inputs
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [21]:
# Sigmoid Derivative to adjust synaptic weights
def sigmoid_derivative(x):
    return x * (1 - x)

In [23]:
# Train
for iteration in range(10_000):
    input_layer = train_x
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = train_y - outputs
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

In [24]:
print("Synaptic Weight: ")
synaptic_weights

Synaptic Weight: 


array([[ 9.67256303],
       [-0.20811174],
       [-4.62926144]])

In [25]:
print("Output: ")
outputs

Output: 


array([[0.00966808],
       [0.99211705],
       [0.99358863],
       [0.00786589]])